name: 'simple-composite-action'
description: 'A Composite Github Action runs some steps'

runs:
  using: 'composite'
  steps:
    - name: Setup
      shell: bash
      run: |
        echo "Set up the composite action" >> $GITHUB_STEP_SUMMARY
    - name: Wrap Up
      shell: bash
      run: |
        echo "Wrap up the composite action" >> $GITHUB_STEP_SUMMARY
       
