name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      inputA:
        description: Number input
        required: true
        type: number
      inputB:
        description: String input
        required: true
        type: string

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/called2.yml
    with:
      inputA: ${{ inputs.inputA }}
      inputB: ${{ inputs.inputB }}
