name: Composite Workflow

on:
  workflow_dispatch:

jobs:
  main-workflow:
    runs-on: self-hosted
    steps:
      - name: Checkout source code from Github
        uses: actions/checkout@v3

      - uses: ./composite
