name: Containes test 2

on:
  workflow_dispatch:
      inputs:
        cleanup:
          default: false
          description: Whether to run clean-up job
          required: false
          type: boolean
env:
  CLEANUP: ${{ inputs.cleanup || false }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: env.CLEANUP
        run: |
          echo A
          echo "$env.CLEANUP"
