name: Containes test 2

on:
  workflow_dispatch:
      inputs:
        cleanup:
          default: false
          description: Whether to run clean-up job
          required: false
          type: boolean
env:
  CLEANUP: ${{ github.event.inputs.cleanup || false }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: env.CLEANUP
        env: 
          TEST: ${{ env.CLEANUP }}
          TEST2: ${{ ${{ github.event.inputs.cleanup}} }}
        run: |
          echo A
          echo "$TEST"
          echo "$TEST2"
