name: Contains Test
on:
  workflow_dispatch:

jobs:
  D:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo D
  A:
    needs: [D]
    if: ${{contains(needs.*.result, 'success') }}
    runs-on: ubuntu-latest
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.result, 'success') }}
    steps:
       - run: |
          echo A
          echo "$NEEDS"
          echo "$CONDITION"
