name: JC_SERV_NO_ACTION
on:
  workflow_dispatch:
jobs:
  my_job:
    runs-on: self-hosted
    services:
      redis:
        image: redis
    container:
      image: alpine:3.15
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - run: pwd
