name: Contains Test
on:
  workflow_dispatch:

jobs:
  D:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - run: echo D
  A:
    needs: [D]
    if: ${{contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo A
          echo "$NEEDS"
          echo "$CONDITION"
