name: Contains Test
on:
  workflow_dispatch:

jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo D
          exit 1
      
  A:
    needs: [D]
    if: ${{contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.result, 'success') }}
    steps:
       - run: |
          echo A
          echo "$NEEDS"
          echo "$CONDITION"
