name: Reproducing GitHub Env Issue
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    #- uses: actions/setup-python@v2
      #with:
        #python-version: '3.x'
    #- run: pip install -r requirements.txt
    - run: python -u scripts/env_example.py