name: Hello world
on:
  workflow_dispatch:
   inputs:
      build_script:
        type: string
        default: "ci/build_cpp.sh"

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
     - name: C++ test
       run: ${{((area=5*5))}}
    
