name: Hello world
on:
  workflow_dispatch:
   inputs:
      build_script:
        type: string
        default: "scripts/hello.py"

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
     - name: C++ test
       run: ${{inputs.build_script}}
    
