# Main Workflow
name: Reproducing issue 1877 (composite)
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Reproducing issue 1877 (composite)
    runs-on: self-hosted
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      # Configure Environments
      - uses: actions/composite-example@main
