name: Reproducing Issue 1512
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         include:
          - os: macos-latest
            version: 12
            environment: prod
          - os: windows-latest
            version: 16
          - os: ubuntu-latest
            version: 16
        

    steps:
      - run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}
