name: Use double quotes
on:
    workflow_dispatch:

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Echo hello world
              if: github.event_name != 'workflow_dispatch'
              run: echo "Hello world!"
