name: Reproducing Issue 1512
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key1: [val1, val3, val5, val8]
        key2: [val2, val4, val6, val8]
        key3: [val7, val10]
        exclude:
          - key1: val1
            key2: val2

    steps:
      - run: |
          echo ${{ matrix.key1 }}
          echo ${{ matrix.key2 }}
          echo ${{ matrix.key3 }}
