name: Reproducing Issue 1533
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-bullseye
    steps:
    - name: Debug Shell
      run: echo $0
    - name: Debug Bash Shell
      run: echo $0
      shell: bash
    - name: Debug sh Shell
      run: echo $0
      shell: sh
