name: Reproducing issue 1835
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: "ubuntu"
          - os: macos-latest
            name: "macOS"
        os: [ubuntu-latest, macos-latest]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        env:
          OS: ${{ matrix.name }}
        run: echo "::set-output name=test::hello world from $OS"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
