name: Reproducing Issue 1512
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key1:
          - val1
        key2:
          - val2
        key3:
          - ""
        
        include:
          - key1: val1
            key2: val2
            
          - key1: val3
            key2: val4
            
          - key1: val5
            key2: val6
            key3: val7
            
          - key1: val8
            key2: val9
            key3: val10

        exclude:
          - key1: val1
            key2: val2

    steps:
      - run: |
          echo ${{ matrix.key1 }}
          echo ${{ matrix.key2 }}
          echo ${{ matrix.key1 }}
          echo ${{ matrix.key2 }}
          echo ${{ matrix.key3 }}
