name: Reproducing issue 763

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Enable problem matcher
        run: echo "::add-matcher::.github/workflows/problem_matchers/multiline_matcher.json"

      - name: Run linter
        run: npm run lint
