name: Test
on:   
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - run: echo prep
  job1:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - run: echo Job1

  job2:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - run: echo Job2
      
  job3:
    needs: prep
    runs-on: ubuntu-latest
    steps:
      - run: echo Job3

  test-output:
    runs-on: ubuntu-latest
    needs: [job1,job2,job3]
    if: ${{ always() && contains(needs.*.result, 'success') }}
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.result, 'success') }}
    steps:
      - run: |
          echo "$NEEDS"
          echo "$CONDITION"
