name: One job script workflow
on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test call
      run: python3 -u scripts/hello.py
