name: One job script workflow
on:
  workflow_dispatch:
  inputs:
      build_script:
        type: string
        default: "scripts/test.sh"

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test call
      run: ${{inputs.build_script}}
