name: One job script workflow
on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: test call
      uses: actions/checkout@v2
      run: python3 -u scripts/hello.py
