name: Recreating issue 1705

on:
  workflow_dispatch:

jobs:
  macos:
    name: ${{matrix.vector.jobname}} (${{matrix.vector.pool}})
    strategy:
      fail-fast: false
      matrix:
        vector:
          - jobname: osx-gcc
            cc: gcc-11
            cxx: g++-11
            pool: macos-10.15
          - jobname: osx-clang
            cc: clang
            cxx: clang++
            pool: macos-10.15
    env:
      CC: ${{matrix.vector.cc}}
      CXX: ${{matrix.vector.cxx}}
      jobname: ${{matrix.vector.jobname}}
      runs_on_pool: ${{matrix.vector.pool}}
      CFLAGS: "-I/usr/local/include -g3 -O0"
    runs-on: ${{matrix.vector.pool}}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:  brew install gmp gettext dejagnu
    - name: Setup codesigning certificate
      run:  |
          sudo DevToolsSecurity -enable
          bash -x gdb/contrib/macos-setup-codesign.sh
    - name: Build
      run: |
          mkdir ../build && cd ../build
          ../binutils-gdb/configure             \
            CC=$CC CXX=$CXX                     \
            CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" \
            --enable-codesign=gdb_codesign      \
            --disable-binutils                  \
            --disable-dependency-tracking       \
            --with-gmp=$(brew --prefix gmp)     \
            --with-libgmp-prefix=$(brew --prefix gmp) \
            --prefix=$HOME/GDB/
          make -j 3
          make install-gdb
          tar -cf $HOME/gdb.tar $HOME/GDB
#    - name: Upload
#      uses: actions/upload-artifact@v2
#      with:
#        name: gdb-11.1.wip
#        path: ~/gdb.tar
    - name: Test
      run: |
          echo 'set startup-with-shell off' > $HOME/.gdbinit
          cd ../build
          make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS='-nw -data-directory $PWD/gdb/data-directory -iex \"set height 0\" -iex \"set width 0\"' CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
#    - name: Setup tmate session
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#
