name: Reusable
on:
  workflow_call:
    outputs:
      pass:
        value: ${{ toJSON(needs) }}
      fail:
        value: ${{ toJSON(jobs) }}

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  pass:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
