name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: self-hosted
    uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    runs-on: self-hosted
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
