name: run python script
  # Controls when the workflow will run
  on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  jobs:
    build:
      runs-on: self-hosted

      steps:
        -name: execute python script
          run: |
            python scripts/hello.py