name: Test
on:   
  push:

jobs:
  D:
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo D
  A:
    needs: [D]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    needs: [A,B]
    if: ${{ !cancelled() && contains(needs.*.result, 'success') == 'true' }}
    steps:
      - run: echo C
