name: Test
on:   
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: out
        run: echo Job1

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo Job2
      
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo Job3

  test-output:
    if: always() && contains(needs.*.result, 'success') == 'true'
    needs: [job1,job2,job3]
    runs-on: ubuntu-latest
    env:
      NEEDS: ${{ toJSON(needs) }}
      CONDITION: ${{ contains(needs.*.result, 'success') }}
    steps:
      - run: |
          echo "$NEEDS"
          echo "$CONDITION"
