name: issue 2224 test
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: [ windows]
    #runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        shell: bash
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        shell: bash
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: [self-hosted, windows, csd-back]
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
