name: Test
on:
  workflow_dispatch:

jobs:
  D:
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo D
  A:
    needs: [D]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo A
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo B
  C:
    runs-on: ubuntu-latest
    if: ${{ always() && !!contains(join(needs.*.result, ','), 'success') }}
    needs: [A,B]
    steps:
      - name: Needs test    
        env:
          NEEDS: ${{ contains(join(needs.*.result, ','), 'success') }}     
        run: |
          echo "$NEEDS"
