name: Caller Workflow
on: workflow_dispatch

jobs:
  job1:
    uses: ./.github/workflows/reusable.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}