name: 'ci'

on: [workflow_dispatch]

jobs:
  run-ui-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [18]
        runOnlyUbuntu:
          - ${{ github.workspace == '/home/runner/work/git-runner-test/git-runner-test' }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Show github json
        run: |
          echo "workspace: ${{ github.workspace }}"
          echo "runOnlyUbuntu: ${{ matrix.runOnlyUbuntu }}"
          echo $JSON
        env:
          JSON: "${{ toJSON(github) }}"
        
      - name: Check event_name event with a contains
        if: contains('workflow_dispatch', github.event_name)
        run: |
          echo "My event type is: ${{ github.event_name }}"
          echo ${{github.workspace}}
      - name: Check github.workspace full path in conditional
        if: github.workspace == '/home/runner/work/git-runner-test/git-runner-test'
        run: |
          echo "Should only run on Ubuntu: ${{ github.workspace }}"
          echo "${{contains('\/Users\/runner\/work\/**', github.workspace)}}"
          echo "${{contains('\/Users\/runner\/work\/*', github.workspace)}}"
          echo "${{contains('/Users/runner/work/*', github.workspace)}}"
          echo "${{contains('/Users/runner/work/**', github.workspace)}}"
      - name: Check workspace for macos
        if: contains('\/Users\/runner\/work\/**', github.workspace)
        run: |
          echo "I'm running on ubuntu-latest: ${{ matrix.os }}"
      - name: Check workspace for ubuntu
        if: contains('\/Users\/runner\/work\/**', github.workspace)
        run: |
          echo "I'm running on ubuntu-latest: ${{ matrix.os }}"
