name: security gits
on:
  workflow_dispatch:

jobs:
  jobmy:
    runs-on: self-hosted
    steps:
      - name: set env normal
        run: echo "myenvvar=val1" > $GITHUB_ENV
        shell: bash
      - name: check env
        run: echo $myenvvar
        shell: bash
      - name: set env injected
        run: echo "TEST_ENV=hello\0injected=itworked)" > $GITHUB_ENV
        shell: bash
      - name: check injected env
        run: echo $TEST_ENV
        shell: bash
   
   
