name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: 'ubuntu-latest'
    steps:
      - name: test
        env: 
          TEST: test
        uses: ruvceskistefan/reusable-workflows/.github/workflows/hello_world.yml@main
